# config file version
apiVersion: 1


datasources:
  # <string, required> name of the datasource. Required
- name: Prometheus
  # <string, required> datasource type. Required
  type: prometheus
  # <string, required> access mode. direct or proxy. Required
  access: proxy
  # <int> org id. will default to orgId 1 if not specified
  orgId: 1
  # <string> url
  url: http://localhost:9090
  isDefault: true
  version: 1
  # <bool> allow users to edit datasources from the UI.
  editable: true

- name: Postgres
  type: postgres
  url: localhost:5432
  user: ${POSTGRES_USER}
  secureJsonData:
    password: ${POSTGRES_PASSWORD}
  jsonData:
    database: ${POSTGRES_DB}
    sslmode: 'disable'
    maxOpenConns: 100
    maxIdleConns: 100
    maxIdleConnsAuto: true
    connMaxLifetime: 14400
    postgresVersion: 903
    timescaledb: false
