[project]
authors = ["Kostas Vilkelis <k.vilkelis@vu.nl>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "feed4food"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.13.1,<4"
psycopg2 = ">=2.9.9,<3"
tzdata = ">=2024b,<2025a"
django-crispy-forms = ">=2.3,<3"
crispy-bootstrap5 = ">=2024.10,<2025"
dash = ">=2.18.2,<3"
plotly = ">=5.24.1,<6"
django-plotly-dash = ">=2.4.3,<3"
ipykernel = ">=6.29.5,<7"
django-extensions = ">=3.2.3,<4"
pandas = ">=2.2.3,<3"
whitenoise = ">=6.7.0,<7"
dash-bootstrap-components = ">=1.6.0,<2"
django-bootstrap4 = ">=3.0.1,<4"
flask = ">=2.1.0,<3"
werkzeug = "==2.2.2"
gunicorn = ">=23.0.0,<24"

[pypi-dependencies]
django-prometheus = ">=2.3.1, <3"
dpd-static-support = ">=0.0.5, <0.0.6"
channels = "*"
daphne = ">=4.1.2, <5"
redis = ">=5.2.1, <6"
django-redis = ">=5.4.0, <6"
channels-redis = ">=4.2.1, <5"
