[project]
authors = ["Kostas Vilkelis <k.vilkelis@vu.nl>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "feed4food"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.13.1,<4"
psycopg2 = ">=2.9.9,<3"
tzdata = ">=2024b,<2025a"
django-crispy-forms = ">=2.3,<3"
crispy-bootstrap5 = ">=2024.10,<2025"
django = ">=5.1.4,<6"
