[project]
authors = ["Kostas Vilkelis <k.vilkelis@vu.nl>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "feed4food"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.13.1,<4"
fastapi = ">=0.115.6,<0.116"
uvicorn = ">=0.32.1,<0.33"
psycopg2 = ">=2.9.9,<3"
sqlalchemy = ">=2.0.36,<3"
pydantic = ">=2.10.3,<3"
passlib = ">=1.7.4,<2"
