select 'dynamic' as component WHERE component = 'shell' LIMIT 1;

--L of water harvested
--INSERT INTO metric1 (m_date,m_value) VALUES (:report_date,:measurement1_value);

--Kg of vegetables

--Test
INSERT INTO test_metric4(m_value,m_date) SELECT value , :report_date FROM json_each($Product_values);
WITH updated as (SELECT value FROM json_each($Product_names))
UPDATE test_metric4 SET m_product = updated.value FROM updated WHERE test_metric4.m_value IN (SELECT value FROM json_each($Product_values));
--INSERT INTO test_metric4(m_product,m_date) SELECT value, :report_date FROM json_each($Product_names) where m_value IN (SELECT value FROM json_each($Product_values));
--(SELECT value as m_value FROM json_each($Product_values)), (SELECT value as m_product FROM json_each($Product_names));
--INSERT INTO metric2(m_date,m_product,m_value) VALUES (:report_date,SELECT value FROM json_each($Product_names), SELECT value FROM json_each($Product_values)) ;

select 'hero' as component,
    'Upload confirmation' as title,
    'Your data has been saved.' as description_md,
    'http://feed4food.eu/wp-content/uploads/2024/01/AdobeStock_594754741-scaled.jpeg' as image;


--select 'datagrid' as component, 'plane-departure' as icon, 'Flight SQL-966' as title, 'Gate closes: ' || :departure_date || ' at 8AM' as description;
--select 
--    'Payment'  as title,
--    'processed' as description,
--    'https://upload.wikimedia.org/wikipedia/commons/2/2a/Mastercard-logo.svg' as image_url;
---select 
--    'Status' as title,
--    'Confirmed' as description,
--    'green'  as color;


--select 'list' as component, 'Value entered' as title, 'users' as icon;
--select value as title, 'Adult' as description, 'user' as icon from json_each(:adult_names);
--select value as title, 'Child' as description, 'baby-carriage' as icon from json_each(:child_names);

--select 'divider' as component, 'Technical details' as contents;

--select 'text' as component, '
--# How is this even possible ?

--Not a single line of *HTML*, *CSS*, *JavaScript*, *Python*, *PHP* or *Ruby* was written to implement 
--SQLPage Airlines'' multi-step, conditional booking process. How is this even possible ?

--The entire form and result page are dynamically generated by a few simple SQL queries, that 
--select graphical components from [SQLPage''s component library](/documentation.sql).

--You can find the [**full source code** of this example on GitHub](https://github.com/lovasoa/SQLpage/blob/main/examples/official-site/examples/multistep-form).
--' as contents_md;

select 
    'button' as component,
	'center' as justify;
select 
    '/index.sql' as link,
    'Home'            as title;