# Generated by Django 5.1.4 on 2024-12-12 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daily_reports', '0002_item_itemdetail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProduceReport',
        ),
        migrations.RemoveField(
            model_name='itemdetail',
            name='key',
        ),
    ]
