# Generated by Django 5.1.4 on 2024-12-12 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_reports', '0004_farmingreport_farmingitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
