# Generated by Django 5.1.4 on 2024-12-12 16:20

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daily_reports', '0005_itemname'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FarmingItem',
            new_name='ProduceItem',
        ),
        migrations.RenameModel(
            old_name='FarmingReport',
            new_name='ProduceReport',
        ),
        migrations.RemoveField(
            model_name='itemdetail',
            name='item',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='ItemDetail',
        ),
    ]
